In [1]:
import numpy as np
import pandas as pd

1. Pandas version (1 point)

In [8]:
pd.__version__

'3.0.6'

In [3]:
URL = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
df = pd.read_csv(URL)

In [7]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

2. Records count (1 point):

In [9]:
df.shape

(10000, 11)

3. Fuel types (1 point)

In [12]:
df["fuel_type"].nunique()

3

4. Missing values (1 point)

In [15]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

5. Max fuel efficiency (1 point)

In [18]:
df.groupby("origin")["fuel_efficiency_mpg"].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

6. Median value of horsepower (1 point)

In [17]:
df["horsepower"].median()

np.float64(254.0)

In [23]:
df["horsepower"].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [26]:
values = df["horsepower"].value_counts()

In [37]:
most_frequent = values.index[0]
most_frequent

np.float64(252.0)

In [41]:
df["horsepower"] = df["horsepower"].fillna(most_frequent)

In [42]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [43]:
df["horsepower"].median()

np.float64(252.0)

7. Sum of weights (1 point)

In [47]:
df_asia = df[df["origin"] == "Asia"]
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [50]:
df_asia_fil = df_asia[["vehicle_weight","model_year"]]
df_asia_fil.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [56]:
X = np.array(df_asia_fil.head(7).values)
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [57]:
XTX = X.T.dot(X)

In [58]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [59]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [60]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [62]:
w = (XTX_inverse.dot(X.T)).dot(y)
w

array([0.13644777, 0.2327492 ])

In [63]:
w.sum()

np.float64(0.36919696904925486)